name: Build JDK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          build-essential \
          autoconf \
          make \
          zip \
          unzip \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          libxtst-dev \
          libcups2-dev \
          libfontconfig1-dev \
          libasound2-dev

      - name: Clone JDK repository
        run: git clone https://git.openjdk.java.net/jdk/

      - name: Configure
        run: |
          cd jdk
          bash configure

      - name: Build JDK
        run: |
          cd jdk
          make images

      - name: Verify JDK build
        run: |
          ./build/*/images/jdk/bin/java -version

      - name: Run basic tests
        run: |
          cd jdk
          make run-test-tier1
